networks:
  utn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/24"
        # especificamos el rango de IP, al poner /24 tenemos 255 números para
        # identificar a una máquina dentro de la red
    external: false

volumes:
  postgres-db:
    external: false

services:
  servidor:
    image: postgres
    container_name: servidor
    restart: unless-stopped
    # significa que si se reinicia el contenedor, se reinicia el servicio automáticamente
    env_file:
      - .env.db
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 2s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      # indicamos que como archivo de configuración usemos uno que nosotros configuremos
      - ./initdb:/docker-entrypoint-initdb.d # apenas inicie que tome estos valores
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    ports:
      - 5435:5432
    networks:
      utn:
        ipv4_address: 172.24.2.10